package com.meher.jawhar.design

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
class JawharColors(
    val isDark: Boolean,
    val bgBase: Color,
    val bgSurface: Color,
    val bgSurfaceVariant: Color,
    val bgSurfaceHigh: Color,
    val bgInverse: Color,
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val primarySoft: Color,
    val accent: Color,
    val onAccent: Color,
    val accentContainer: Color,
    val onAccentContainer: Color,
    val info: Color,
    val infoContainer: Color,
    val error: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val success: Color,
    val successContainer: Color,
    val onSurface: Color,
    val onSurfaceVariant: Color,
    val onSurfaceSubtle: Color,
    val onInverse: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,
    val roleFaail: Color,
    val roleMaful: Color,
    val roleMubtada: Color,
    val roleKhabar: Color,
    val roleNat: Color,
    val roleHarf: Color,
    val roleMudaf: Color,
)

val JawharLightColors = JawharColors(
    isDark = false,
    bgBase = Color(0xFFFBF7EE),
    bgSurface = Color(0xFFFEFCF7),
    bgSurfaceVariant = Color(0xFFF5EFE0),
    bgSurfaceHigh = Color(0xFFEBE3CE),
    bgInverse = Color(0xFF062A25),
    primary = Color(0xFF0F4A41),
    onPrimary = Color(0xFFFEFCF7),
    primaryContainer = Color(0xFFCFE6E0),
    onPrimaryContainer = Color(0xFF062A25),
    primarySoft = Color(0xFFEAF4F1),
    accent = Color(0xFFE2A82A),
    onAccent = Color(0xFF031815),
    accentContainer = Color(0xFFFCEBBE),
    onAccentContainer = Color(0xFF523805),
    info = Color(0xFF264A8A),
    infoContainer = Color(0xFFD2DFF5),
    error = Color(0xFFA3402D),
    errorContainer = Color(0xFFF8D9D1),
    onErrorContainer = Color(0xFF7F3022),
    success = Color(0xFF2F7340),
    successContainer = Color(0xFFD3E9D0),
    onSurface = Color(0xFF1F1C15),
    onSurfaceVariant = Color(0xFF6F6650),
    onSurfaceSubtle = Color(0xFF968B72),
    onInverse = Color(0xFFFBF7EE),
    outline = Color(0xFFDDD2B8),
    outlineVariant = Color(0xFFEBE3CE),
    scrim = Color(0x80050F0D),
    roleFaail = Color(0xFF2F8F5B),
    roleMaful = Color(0xFF3A66B0),
    roleMubtada = Color(0xFFC9971A),
    roleKhabar = Color(0xFFD9822B),
    roleNat = Color(0xFF7B5AA6),
    roleHarf = Color(0xFF8B8268),
    roleMudaf = Color(0xFFC0587A),
)

val JawharDarkColors = JawharColors(
    isDark = true,
    bgBase = Color(0xFF0D1513),
    bgSurface = Color(0xFF121C19),
    bgSurfaceVariant = Color(0xFF182420),
    bgSurfaceHigh = Color(0xFF21302B),
    bgInverse = Color(0xFFF5EFE0),
    primary = Color(0xFF6FB3A5),
    onPrimary = Color(0xFF031815),
    primaryContainer = Color(0xFF0A3A33),
    onPrimaryContainer = Color(0xFFCFE6E0),
    primarySoft = Color(0xFF062A25),
    accent = Color(0xFFEFC04F),
    onAccent = Color(0xFF031815),
    accentContainer = Color(0xFF523805),
    onAccentContainer = Color(0xFFFCEBBE),
    info = Color(0xFF7A9AD8),
    infoContainer = Color(0xFF14274B),
    error = Color(0xFFE59A88),
    errorContainer = Color(0xFF7F3022),
    onErrorContainer = Color(0xFFF8D9D1),
    success = Color(0xFF8CC796),
    successContainer = Color(0xFF1E4A29),
    onSurface = Color(0xFFF5EFE0),
    onSurfaceVariant = Color(0xFFBDB195),
    onSurfaceSubtle = Color(0xFF968B72),
    onInverse = Color(0xFF062A25),
    outline = Color(0xFF2D3F39),
    outlineVariant = Color(0xFF21302B),
    scrim = Color(0x99000000),
    roleFaail = Color(0xFF6CCB93),
    roleMaful = Color(0xFF8FB0EA),
    roleMubtada = Color(0xFFF0CB5E),
    roleKhabar = Color(0xFFF2A862),
    roleNat = Color(0xFFB79BE0),
    roleHarf = Color(0xFFB8AE93),
    roleMudaf = Color(0xFFE89BB4),
)

val ShadowTint = Color(0xFF052924)
