"""extend words morphology fields, add nahw_annotations

Revision ID: 12960b53420f
Revises: a761919d949b
Create Date: 2026-10-04 00:58:23.220041

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '12960b53420f'
down_revision: str | None = 'a761919d949b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nahw_annotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('verse_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('token_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('dep_type', sa.String(length=50), nullable=True),
    sa.Column('head_index', sa.Integer(), nullable=True),
    sa.Column('irab', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['verse_id'], ['verses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verse_id', 'token_index', name='uq_nahw_verse_token')
    )
    op.create_index(op.f('ix_nahw_annotations_verse_id'), 'nahw_annotations', ['verse_id'], unique=False)
    op.create_index(op.f('ix_nahw_annotations_word_id'), 'nahw_annotations', ['word_id'], unique=False)
    op.add_column('words', sa.Column('pattern', sa.String(length=50), nullable=True))
    op.add_column('words', sa.Column('tense', sa.String(length=30), nullable=True))
    op.add_column('words', sa.Column('voice', sa.String(length=30), nullable=True))
    op.add_column('words', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('words', sa.Column('number', sa.String(length=20), nullable=True))
    op.add_column('words', sa.Column('person', sa.String(length=20), nullable=True))
    op.add_column('words', sa.Column('features_json', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_words_lemma'), 'words', ['lemma'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_lemma'), table_name='words')
    op.drop_column('words', 'features_json')
    op.drop_column('words', 'person')
    op.drop_column('words', 'number')
    op.drop_column('words', 'gender')
    op.drop_column('words', 'voice')
    op.drop_column('words', 'tense')
    op.drop_column('words', 'pattern')
    op.drop_index(op.f('ix_nahw_annotations_word_id'), table_name='nahw_annotations')
    op.drop_index(op.f('ix_nahw_annotations_verse_id'), table_name='nahw_annotations')
    op.drop_table('nahw_annotations')
    # ### end Alembic commands ###
