"""Initial schema: users, refresh_tokens, surahs, verses, words

Revision ID: a761919d949b
Revises:
Create Date: 2026-09-27 14:35:40.446895

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a761919d949b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surahs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name_arabic', sa.String(length=100), nullable=False),
    sa.Column('name_transliteration', sa.String(length=100), nullable=False),
    sa.Column('name_english', sa.String(length=100), nullable=False),
    sa.Column('revelation_place', sa.String(length=10), nullable=True),
    sa.Column('verse_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('native_lang', sa.String(length=10), nullable=False),
    sa.Column('ui_lang', sa.String(length=10), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('learning_goal', sa.String(length=50), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_review_date', sa.Date(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('onb_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_refresh_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('verses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('surah_id', sa.Integer(), nullable=False),
    sa.Column('ayah_number', sa.Integer(), nullable=False),
    sa.Column('text_uthmani', sa.Text(), nullable=False),
    sa.Column('text_imlaei', sa.Text(), nullable=True),
    sa.Column('translation_en', sa.Text(), nullable=True),
    sa.Column('translation_ur', sa.Text(), nullable=True),
    sa.Column('juz_number', sa.Integer(), nullable=True),
    sa.Column('hizb_number', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['surah_id'], ['surahs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('surah_id', 'ayah_number', name='uq_verse_surah_ayah')
    )
    op.create_index(op.f('ix_verses_surah_id'), 'verses', ['surah_id'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('verse_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text_uthmani', sa.Text(), nullable=False),
    sa.Column('text_imlaei', sa.Text(), nullable=True),
    sa.Column('translation_en', sa.Text(), nullable=True),
    sa.Column('transliteration', sa.Text(), nullable=True),
    sa.Column('root', sa.String(length=50), nullable=True),
    sa.Column('lemma', sa.String(length=100), nullable=True),
    sa.Column('pos_tag', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['verse_id'], ['verses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verse_id', 'position', name='uq_word_verse_pos')
    )
    op.create_index(op.f('ix_words_root'), 'words', ['root'], unique=False)
    op.create_index(op.f('ix_words_verse_id'), 'words', ['verse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_verse_id'), table_name='words')
    op.drop_index(op.f('ix_words_root'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_verses_surah_id'), table_name='verses')
    op.drop_table('verses')
    op.drop_index('idx_refresh_user', table_name='refresh_tokens')
    op.drop_index('idx_refresh_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('surahs')
    # ### end Alembic commands ###
