"""add decks table and srs_cards.deck_id

Revision ID: b8cfafcfbe10
Revises: 818ef059a1b3
Create Date: 2026-10-04 15:56:34.393274

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b8cfafcfbe10'
down_revision: str | None = '818ef059a1b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decks_user', 'decks', ['user_id'], unique=False)
    op.create_table('srs_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('surah_number', sa.Integer(), nullable=True),
    sa.Column('ayah_number', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_srs_cards_deck_id'), 'srs_cards', ['deck_id'], unique=False)
    op.create_index('ix_srs_cards_user_due', 'srs_cards', ['user_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_srs_cards_user_id'), 'srs_cards', ['user_id'], unique=False)
    op.create_index('ix_srs_cards_user_state', 'srs_cards', ['user_id', 'state'], unique=False)
    op.create_index(op.f('ix_srs_cards_word_id'), 'srs_cards', ['word_id'], unique=False)
    op.create_table('srs_review_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_duration_ms', sa.Integer(), nullable=True),
    sa.Column('previous_interval_days', sa.Integer(), nullable=False),
    sa.Column('new_interval_days', sa.Integer(), nullable=False),
    sa.Column('previous_ease_factor', sa.Float(), nullable=False),
    sa.Column('new_ease_factor', sa.Float(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['srs_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_srs_logs_user_reviewed', 'srs_review_logs', ['user_id', 'reviewed_at'], unique=False)
    op.create_index(op.f('ix_srs_review_logs_card_id'), 'srs_review_logs', ['card_id'], unique=False)
    op.create_index(op.f('ix_srs_review_logs_user_id'), 'srs_review_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_srs_review_logs_user_id'), table_name='srs_review_logs')
    op.drop_index(op.f('ix_srs_review_logs_card_id'), table_name='srs_review_logs')
    op.drop_index('ix_srs_logs_user_reviewed', table_name='srs_review_logs')
    op.drop_table('srs_review_logs')
    op.drop_index(op.f('ix_srs_cards_word_id'), table_name='srs_cards')
    op.drop_index('ix_srs_cards_user_state', table_name='srs_cards')
    op.drop_index(op.f('ix_srs_cards_user_id'), table_name='srs_cards')
    op.drop_index('ix_srs_cards_user_due', table_name='srs_cards')
    op.drop_index(op.f('ix_srs_cards_deck_id'), table_name='srs_cards')
    op.drop_table('srs_cards')
    op.drop_index('ix_decks_user', table_name='decks')
    op.drop_table('decks')
    # ### end Alembic commands ###
