package com.meher.jawhar.screens

import androidx.compose.runtime.Composable
import com.meher.jawhar.design.JawharTheme
import com.meher.jawhar.nav.Dest

class ScreenSpec(
    val id: String,
    val group: String,
    val title: String,
    val wide: Boolean = false,
    val content: @Composable () -> Unit,
)

object Screens {
    private fun dark(id: String, title: String, content: @Composable () -> Unit) =
        ScreenSpec(id, "Dark mode", title) { JawharTheme(dark = true) { content() } }

    val all: List<ScreenSpec> = listOf(
        ScreenSpec(Dest.Splash, "1 · Onboarding and auth", "01 Splash") { SplashScreen() },
        ScreenSpec(Dest.Welcome1, "1 · Onboarding and auth", "02 Welcome: understand") { WelcomeScreen(0) },
        ScreenSpec(Dest.Welcome2, "1 · Onboarding and auth", "03 Welcome: Sarf and Nahw") { WelcomeScreen(1) },
        ScreenSpec(Dest.Welcome3, "1 · Onboarding and auth", "04 Welcome: AI tutor") { WelcomeScreen(2) },
        ScreenSpec(Dest.GetStarted, "1 · Onboarding and auth", "05 Get started") { GetStartedScreen() },
        ScreenSpec(Dest.SignUp, "1 · Onboarding and auth", "06 Sign up") { SignUpScreen() },
        ScreenSpec(Dest.LogIn, "1 · Onboarding and auth", "07 Log in") { LogInScreen() },
        ScreenSpec(Dest.Forgot, "1 · Onboarding and auth", "08 Forgot password") { ForgotPasswordScreen() },
        ScreenSpec(Dest.Verify, "1 · Onboarding and auth", "09 Verify email") { VerifyEmailScreen() },
        ScreenSpec(Dest.PlacementIntro, "1 · Onboarding and auth", "10 Placement intro") { PlacementIntroScreen() },
        ScreenSpec(Dest.PlacementQuestion, "1 · Onboarding and auth", "11 Placement question") { PlacementQuestionScreen() },
        ScreenSpec(Dest.PlacementResult, "1 · Onboarding and auth", "12 Placement result") { PlacementResultScreen() },
        ScreenSpec(Dest.DailyGoal, "1 · Onboarding and auth", "13 Daily goal") { DailyGoalScreen() },
        ScreenSpec(Dest.NotifPermission, "1 · Onboarding and auth", "14 Notification permission") { NotificationPermissionScreen() },
        ScreenSpec(Dest.Home, "2 · Home and learn", "15 Home") { HomeScreen() },
        ScreenSpec(Dest.Learn, "2 · Home and learn", "16 Learning path") { LearnPathScreen() },
        ScreenSpec(Dest.LessonIntro, "2 · Home and learn", "17 Lesson intro") { LessonIntroScreen() },
        ScreenSpec(Dest.LessonContent, "2 · Home and learn", "18 Lesson content") { LessonContentScreen() },
        ScreenSpec(Dest.LessonQuiz, "2 · Home and learn", "19 Lesson quiz") { LessonQuizScreen() },
        ScreenSpec(Dest.LessonComplete, "2 · Home and learn", "20 Lesson complete") { LessonCompleteScreen() },
        ScreenSpec(Dest.DailyChallenge, "2 · Home and learn", "21 Daily challenge") { DailyChallengeScreen() },
        ScreenSpec(Dest.Quran, "3 · Quran, Sarf and Nahw", "22 Surah list") { SurahListScreen() },
        ScreenSpec(Dest.Reader, "3 · Quran, Sarf and Nahw", "23 Ayah reader") { AyahReaderScreen() },
        ScreenSpec("wordPopup", "3 · Quran, Sarf and Nahw", "24 Word popup") { AyahReaderScreen(showPopup = true) },
        ScreenSpec(Dest.Sarf, "3 · Quran, Sarf and Nahw", "25 Sarf Engine") { SarfEngineScreen() },
        ScreenSpec(Dest.WordFamily, "3 · Quran, Sarf and Nahw", "26 Word family") { WordFamilyScreen() },
        ScreenSpec(Dest.Conjugation, "3 · Quran, Sarf and Nahw", "27 Conjugation") { ConjugationScreen() },
        ScreenSpec(Dest.NahwInput, "3 · Quran, Sarf and Nahw", "28 Nahw input") { NahwInputScreen() },
        ScreenSpec(Dest.NahwResult, "3 · Quran, Sarf and Nahw", "29 Nahw result") { NahwResultScreen() },
        ScreenSpec(Dest.Search, "3 · Quran, Sarf and Nahw", "30 Search results") { SearchScreen() },
        ScreenSpec(Dest.TutorChat, "4 · Tutor and flashcards", "31 Tutor chat") { TutorChatScreen() },
        ScreenSpec(Dest.TutorStart, "4 · Tutor and flashcards", "32 Tutor start") { TutorStartScreen() },
        ScreenSpec(Dest.TutorHistory, "4 · Tutor and flashcards", "33 Tutor history") { TutorHistoryScreen() },
        ScreenSpec(Dest.FlashFront, "4 · Tutor and flashcards", "34 Flashcard front") { FlashcardScreen() },
        ScreenSpec(Dest.FlashBack, "4 · Tutor and flashcards", "35 Flashcard back") { FlashcardScreen(showBack = true) },
        ScreenSpec(Dest.ReviewDone, "4 · Tutor and flashcards", "36 Review complete") { ReviewCompleteScreen() },
        ScreenSpec(Dest.Vocab, "4 · Tutor and flashcards", "37 Vocabulary library") { VocabularyScreen() },
        ScreenSpec(Dest.Progress, "5 · Progress and profile", "38 Progress") { ProgressScreen() },
        ScreenSpec(Dest.Leaderboard, "5 · Progress and profile", "39 Leaderboard") { LeaderboardScreen() },
        ScreenSpec(Dest.Badges, "5 · Progress and profile", "40 Badges") { BadgesScreen() },
        ScreenSpec(Dest.Profile, "5 · Progress and profile", "41 Profile") { ProfileScreen() },
        ScreenSpec(Dest.Settings, "5 · Progress and profile", "42 Settings") { SettingsScreen() },
        ScreenSpec(Dest.EditProfile, "5 · Progress and profile", "43 Edit profile") { EditProfileScreen() },
        ScreenSpec(Dest.Appearance, "5 · Progress and profile", "44 Appearance and reading") { AppearanceScreen() },
        ScreenSpec(Dest.NotifSettings, "5 · Progress and profile", "45 Notification settings") { NotificationSettingsScreen() },
        ScreenSpec(Dest.Help, "5 · Progress and profile", "46 Help and About") { HelpAboutScreen() },
        ScreenSpec("s_login_error", "6 · States and edge cases", "S01 Log in error") { LogInScreen(error = true) },
        ScreenSpec("s_signup_validation", "6 · States and edge cases", "S02 Sign up validation") { SignUpScreen(validation = true) },
        ScreenSpec("s_reset_sent", "6 · States and edge cases", "S03 Reset link sent") { ResetSentScreen() },
        ScreenSpec("s_session_expired", "6 · States and edge cases", "S04 Session expired") { SessionExpiredScreen() },
        ScreenSpec("s_no_internet", "6 · States and edge cases", "S05 No internet") { NoInternetScreen() },
        ScreenSpec("s_offline_banner", "6 · States and edge cases", "S06 Offline banner") { OfflineBannerScreen() },
        ScreenSpec("s_server_error", "6 · States and edge cases", "S07 Server error") { ServerErrorScreen() },
        ScreenSpec("s_analyser_timeout", "6 · States and edge cases", "S08 Analyser timeout") { SarfEngineScreen(timeout = true) },
        ScreenSpec("s_tutor_error", "6 · States and edge cases", "S09 Tutor error") { TutorChatScreen(error = true) },
        ScreenSpec("s_not_found", "6 · States and edge cases", "S10 Content not found") { NotFoundScreen() },
        ScreenSpec("s_maintenance", "6 · States and edge cases", "S11 Maintenance") { MaintenanceScreen() },
        ScreenSpec("s_update_required", "6 · States and edge cases", "S12 Update required") { UpdateRequiredScreen() },
        ScreenSpec("s_empty_bookmarks", "6 · States and edge cases", "S13 Empty bookmarks") { EmptyBookmarksScreen() },
        ScreenSpec("s_all_caught_up", "6 · States and edge cases", "S14 All caught up") { AllCaughtUpScreen() },
        ScreenSpec("s_no_results", "6 · States and edge cases", "S15 No search results") { SearchScreen(empty = true) },
        ScreenSpec("s_no_chats", "6 · States and edge cases", "S16 Empty chat history") { TutorHistoryScreen(empty = true) },
        ScreenSpec("s_skeleton_home", "6 · States and edge cases", "S17 Skeleton home") { SkeletonHomeScreen() },
        ScreenSpec("s_skeleton_reader", "6 · States and edge cases", "S18 Skeleton reader") { SkeletonReaderScreen() },
        ScreenSpec("s_notif_denied", "6 · States and edge cases", "S19 Notifications denied") { NotificationsDeniedScreen() },
        ScreenSpec("s_streak_risk", "6 · States and edge cases", "S20 Streak at risk") { StreakAtRiskScreen() },
        ScreenSpec("s_streak_lost", "6 · States and edge cases", "S21 Streak lost") { StreakLostScreen() },
        ScreenSpec("s_level_up", "6 · States and edge cases", "S22 Level up") { LevelUpScreen() },
        ScreenSpec("s_badge_unlocked", "6 · States and edge cases", "S23 Badge unlocked") { BadgeUnlockedScreen() },
        ScreenSpec("s_dialog_logout", "6 · States and edge cases", "S24 Log out dialog") { LogoutDialogScreen() },
        ScreenSpec("s_dialog_delete", "6 · States and edge cases", "S25 Delete account dialog") { DeleteDialogScreen() },
        ScreenSpec("s_dialog_leave", "6 · States and edge cases", "S26 Leave lesson dialog") { LeaveLessonScreen() },
        ScreenSpec("s_snackbars", "6 · States and edge cases", "S27 Snackbars") { SnackbarsScreen() },
        ScreenSpec("s_filter_sheet", "6 · States and edge cases", "S28 Filter sheet") { FilterSheetScreen() },
        dark("d_home", "D01 Home") { HomeScreen() },
        dark("d_learn", "D02 Learning path") { LearnPathScreen() },
        dark("d_reader", "D03 Ayah reader") { AyahReaderScreen() },
        dark("d_nahw", "D04 Nahw result") { NahwResultScreen() },
        dark("d_tutor", "D05 Tutor chat") { TutorChatScreen() },
        dark("d_flash", "D06 Flashcard back") { FlashcardScreen(showBack = true) },
        dark("d_profile", "D07 Profile") { ProfileScreen() },
        ScreenSpec("admin_login", "Admin dashboard (web)", "A01 Admin login", wide = true) { AdminLoginScreen() },
        ScreenSpec("admin_overview", "Admin dashboard (web)", "A02 Overview", wide = true) { AdminOverviewScreen() },
        ScreenSpec("admin_users", "Admin dashboard (web)", "A03 Users", wide = true) { AdminUsersScreen() },
        ScreenSpec("admin_content", "Admin dashboard (web)", "A04 Content editor", wide = true) { AdminContentScreen() },
    )

    val byId: Map<String, ScreenSpec> = all.associateBy { it.id }
}
